apiVersion: policy/v1
kind: PodSecurityPolicy
metadata:
  name: restricted-pss
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1000
      max: 65535
  volumes:
    - 'configMap'
    - 'secret'
    - 'emptyDir'
    - 'projected'
